#ifndef DOWNLOADCODE_H
#define DOWNLOADCODE_H

#include "reg.h"

#define MAXHEXFILE_CODESIZE 1024
REG32 HEXcodeaddr[MAXHEXFILE_CODESIZE];
REG32 HEXcodedata[MAXHEXFILE_CODESIZE];


#endif //DOWNLOADCODE_H