
#include <stdio.h>
#include <string.h>
#include <time.h>

void printtrace(FILE * fp);

void dumpvcdheader(FILE *vcdfp)
{
    char str[100];

    FILE *varfp = fopen("dumpvcd/varids.txt", "r");

    fprintf(vcdfp, "$version Generated by c $end\n");
    time_t t = time(NULL);
    struct tm *tm = localtime(&t);
    fprintf(vcdfp, "$date %s", asctime(tm));fprintf(vcdfp, "$end\n");
    fprintf(vcdfp, "$timescale 1ns $end\n");
    fprintf(vcdfp, "$scope module TOP $end\n");
    //
    while (fgets(str,100,varfp)!=NULL)
    {
        fprintf(vcdfp, "%s",str);
    }
    fclose(varfp);
    //
    fprintf(vcdfp, "$upscope $end\n");
    fprintf(vcdfp, "$enddefinitions $end\n");
    fprintf(vcdfp, "$dumpvars $end\n");
    //
}

void fprintfb(FILE *fp, char * str, unsigned int varvalue)
{
    char *tmp;
    int bitwidth,i;
    tmp = strdup(str);
    tmp[2]='\0';
    //
    fprintf(fp, "b");
    bitwidth = atoi(tmp);
    for (i=0;i<bitwidth;i++)
    {
        fprintf(fp, "%d", (varvalue>>(bitwidth-i-1))&0x01);
    }
    fprintf(fp, " ");
    // varid
    tmp[0]=tmp[3];
    tmp[1]=tmp[4];
    tmp[2]=tmp[5];
    tmp[3]='\0';
    fprintf(fp, "%s\n", tmp);

}

void dumpvars(int clkcnt, FILE *vcdfp)
{
    fprintf(vcdfp, "#%d\n", clkcnt);
    printtrace(vcdfp);
}