#include <stdio.h>
#include <stdlib.h>
#include "dumpvcd.h"

void isconverge_h()
{
    int i;
    char * tmp;
    FILE *dc = fopen("../isconverge.h", "w");
    //
    fprintf(dc, "//\n");
    fprintf(dc, "//This file is generated by program dumpvcd/coverge.c, dont modify it\n");
    fprintf(dc, "//\n");
    fprintf(dc, "#ifndef ISCONVERGE_H\n");
    fprintf(dc, "#define ISCONVERGE_H\n");
    fprintf(dc, "#include \"reg.h\"\n");
    fprintf(dc, "BIT isconverge(BIT debug);\n");
    //
    //
    for (i=0;i<MAXVARSIZE;i++)
    {
        if ((varsize[i])==1)
        {
            if (vararraysize[i]==-1)
                fprintf(dc, "BIT pre_%s;\n",varreferences[i]);
            else{
                tmp = varreferences[i];
                strsep(&tmp, "[");
                fprintf(dc, "BIT pre_%s__%d__;\n",varreferences[i],vararraysize[i]);
            }    
        }
//        else if ((varsize[i])==8)
//        {
//            fprintf(dc, "REG8 pre_%s;\n",varreferences[i]);
//        }
//        else if ((varsize[i])==16)
//        {
//            fprintf(dc, "REG16 pre_%s;\n",varreferences[i]);
//        }
//        else if ((varsize[i])==32)
//        {
//            fprintf(dc, "REG32 pre_%s;\n",varreferences[i]);
//        }
        else if ((varsize[i])!=-1)
        {
            if (vararraysize[i]==-1)
                fprintf(dc, "REG%d pre_%s;\n",varsize[i],varreferences[i]);
            else{
                tmp = varreferences[i];
                strsep(&tmp, "[");
                fprintf(dc, "REG%d pre_%s__%d__;\n",varsize[i],varreferences[i],vararraysize[i]);
            }    
        }
        
    }
    fprintf(dc, "#endif //ISCONVERGE_H\n");
    fclose(dc);

}

void isconverge_c()
{
    int i;
    FILE *dc = fopen("../isconverge.c", "w");
    //
    fprintf(dc, "//\n");
    fprintf(dc, "//This file is generated by program dumpvcd/coverge.c, dont modify it\n");
    fprintf(dc, "//\n");
    fprintf(dc, "#include \"isconverge.h\"\n");
    fprintf(dc, "#include \"reg.h\"\n");
    fprintf(dc, "#include \"fetch.h\"\n");
    fprintf(dc, "#include \"decode.h\"\n");
    fprintf(dc, "#include \"execu.h\"\n");
    fprintf(dc, "#include \"memwb.h\"\n");
    //fprintf(dc, "#include \"regbus.h\"\n");
    //fprintf(dc, "#include \"codebus.h\"\n");
    //fprintf(dc, "#include \"databus.h\"\n");
    //fprintf(dc, "#include \"memwb_bus.h\"\n");
    fprintf(dc, "#include \"mul.h\"\n");
    fprintf(dc, "#include \"divrem.h\"\n");
    fprintf(dc, "#include \"lif.h\"\n");
    fprintf(dc, "#include \"dumpvars.h\"\n");
    fprintf(dc, "#include \"rv16torv32.h\"\n");
    fprintf(dc, "#include \"ext_write_coderam.h\"\n");
    fprintf(dc, "#include \"extbussplit.h\"\n");
    fprintf(dc, "#include \"lsubussplit.h\"\n");
    fprintf(dc, "#include \"ifubussplit.h\"\n");
    fprintf(dc, "#include \"biubussplit.h\"\n");
    fprintf(dc, "#include \"biumerge.h\"\n");
    fprintf(dc, "#include \"itcmmerge.h\"\n");
    fprintf(dc, "#include \"dtcmmerge.h\"\n");
    fprintf(dc, "#include \"regfilemerge.h\"\n");
    fprintf(dc, "#include \"clint.h\"\n");
    fprintf(dc, "#include \"lowclkgen.h\"\n");
    fprintf(dc, "#include \"plic.h\"\n");
    fprintf(dc, "#include \"peripheral.h\"\n");
    fprintf(dc, "#include \"itcm.h\"\n");
    fprintf(dc, "#include \"dtcm.h\"\n");
    fprintf(dc, "#include \"regfile.h\"\n");
    fprintf(dc, "#include \"csrreg.h\"\n");
    fprintf(dc, "#include \"testfinishcheck.h\"\n");
    fprintf(dc, "#include \"exitcheck.h\"\n");
    fprintf(dc, "#include \"perfcheck.h\"\n");
    fprintf(dc, "#include \"uart.h\"\n");
    fprintf(dc, "#include \"gpio.h\"\n");
    fprintf(dc, "#include \"pwm.h\"\n");
    fprintf(dc, "#include \"ctradio.h\"\n");
    fprintf(dc, "\n");
    fprintf(dc, "BIT isconverge(BIT debug){\n");
    fprintf(dc, "BIT converge;\n");
    fprintf(dc, "REG32 converge_index;\n");
    fprintf(dc, "converge=1;\n");
    fprintf(dc, "converge_index=0;\n");

    for (i=0;i<MAXVARSIZE;i++)
    {
        if ((varsize[i])!=-1)
        {
            if (vararraysize[i]==-1)
                fprintf(dc, "converge = converge & (pre_%s==%s);\n",varreferences[i], varreferences[i]);
            else{
                fprintf(dc, "converge = converge & (pre_%s__%d__==%s[%d]);\n",varreferences[i],vararraysize[i], varreferences[i],vararraysize[i]);
            }
            fprintf(dc, "converge_index= converge ? %d : converge_index;\n", i);
        }
        else{
            break;
        }
    }
    fprintf(dc, "if (debug) {printf(\"converge_index=%%d\\n\",converge_index);}\n");

    // update variables
    fprintf(dc, "//update variables\n");
    for (i=0;i<MAXVARSIZE;i++)
    {
        if ((varsize[i])!=-1)
        {
            if (vararraysize[i]==-1)
                fprintf(dc, "pre_%s=%s;\n",varreferences[i], varreferences[i]);
            else{
                fprintf(dc, "pre_%s__%d__=%s[%d];\n",varreferences[i],vararraysize[i], varreferences[i],vararraysize[i]);
            }
        }
        else{
            break;
        }
    }
    //
    fprintf(dc, "return(converge);\n");
    fprintf(dc, "}\n");
    fclose(dc);
    //
    

}